services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      # Mount database volume for persistence
      - ./prisma:/app/prisma
      # Mount uploads or other persistent data if needed
      - app_data:/app/data
    restart: unless-stopped
    networks:
      - app_network

  # For development with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - app_network
    profiles:
      - dev

volumes:
  app_data:

networks:
  app_network:
    driver: bridge